### ISSUE TITLE
Looks like defining a rate > max_rate is valid.

### ISSUE THREAD

**Issue by neurocis** [cosmos/launch#101]
REF: PR#65

In that pull request is a rate which is greater than the max_rate. Unsure if this is allowed and will be defaulted to rate becoming max_rate or a bug.

**Comment by ValarDragon** [comment]
I think this does eventually get checked, and will just make the tx fail? I'm not really sure though. This issue should hopefully move the validation logic so it would be caught here https://github.com/cosmos/cosmos-sdk/issues/3854

/cc @alexanderbez @cwgoes

**Comment by alexanderbez** [comment]
Are you referring to the commission rate? If so, there are two instances in which the validator commission comes into play: (1) when the validator is first created and (2) when the validator updates its commission.

During (1) `SetInitialCommission` is called which calls `Commission#Validate`
During (2) `UpdateValidatorCommission` is called which calls `ValidateNewRate`

There is no place, afaik, where an invalid rate can be initially supplied or updated. As @ValarDragon suggusted, we can and should move all the lazy/basic validation checks to the respective msg's `ValidateBasic`.

**Comment by alexanderbez** [comment]
Unless you mean the certus bot, in which case feel free to reopen :)

**Comment by neurocis** [comment]
certus, yes. If validation happens later, good, but:

```
~/.gaiad # gaiacli tx staking create-validator \
>   --chain-id cosmoshub-1 \
>   --moniker piggy-coin.com \
>   --amount 1000000000uatom \
>   --min-self-delegation 100000000 \
>   --commission-rate 1.75 \
>   --commission-max-rate 0.5 \
>   --commission-max-change-rate 0.005 \
>   --pubkey $(gaiad tendermint show-validator) \
>   --website "https://www.piggy-coin.com/" \
>   --details "Delegate here to support piggy-coin's hard-spoon to tendermint / cosmos" \
>   --identity 9979ae5a5da54bf04719b8c8ebdc0d24 \
>   --from PiggyCoin \
>   --generate-only --indent
{"type":"auth/StdTx","value":{"msg":[{"type":"cosmos-sdk/MsgCreateValidator","value":{"description":{"moniker":"piggy-coin.com","identity":"9979ae5a5da54bf04719b8c8ebdc0d24","website":"https://www.piggy-coin.com/","details":"Delegate here to support piggy-coin's hard-spoon to tendermint/ cosmos"},"commission":{"rate":"1.750000000000000000","max_rate":"0.500000000000000000","max_change_rate":"0.005000000000000000"},"min_self_delegation":"100000000","delegator_address":"cosmos1zp6kg7qlmztyw2km2af4z5ruz5vn04cpq84vjk","validator_address":"cosmosvaloper1zp6kg7qlmztyw2km2af4z5ruz5vn04cp9npe79","pubkey":"cosmosvalconspub1zcjduepq5supzpux2jafyv06qw2dnd0fzshd2enmea9zeak9emu2ft5rs8nswzlqxf","value":{"denom":"uatom","amount":"1000000000"}}}],"fee":{"amount":null,"gas":"200000"},"signatures":null,"memo":""}}
```

should or should not be validated at this initial stage as it will be invalid later?

**Comment by alexanderbez** [comment]
It will be validated when the tx's message gets processed. Although we should provide some basic sanity checks here ☝️

**Comment by neurocis** [comment]
Should one open an issue on the SDK repo?

**Comment by alexanderbez** [comment]
@neurocis an issue, cosmos/cosmos-sdk#3854, is already created to perform lazy/basic validation. But again, please note, that these checks are already done :)
