### ISSUE TITLE
Edit validator Error Insufficient funds to pay for fees on node without fees

### ISSUE THREAD

**Issue by simi-dev** [cosmos/launch#120]
### Commands:

gaiacli tx staking edit-validator --moniker="moniker_name" --website="http://......" --identity="xxxx" --details="xxxxx" --chain-id=cosmoshub-1 --from=key_alias --commission-rate="0.15" --node="xxx.xxx.xxx.xxx:26657" --generate-only > editValidatorUnsignedTx.json

gaiacli tx sign editValidatorUnsignedTx.json --offline --ledger --chain-id="cosmoshub-1" --indent --from=key_alias > editValidatorSignedTx.json

gaiacli tx broadcast editValidatorSignedTx.json --from=key_alias --chain-id="cosmoshub-1" --node="xxx.xxx.xxx:26657"

### Output: 
ERROR: {"codespace":"sdk","code":5,"message":"insufficient funds to pay for fees;  < 5000uatom"}

### Obs:
**--node** is one of our sentries that run without fees
**gaia.toml :**
minimum_fees = ""
minimum-gas-prices = ""

**gaiacli version --long** (installed from scratch)
cosmos-sdk: 0.33.0
git commit: 7b4104aced52aa5b59a96c28b5ebeea7877fc4f0
vendor hash: 
build tags: netgo ledger
go version go1.11.5 darwin/amd64

*if needed i can provide generated json files and full cli commands

**Comment by cwgoes** [comment]
Check your account balance; you may need more funds in your account to pay transaction fees.

**Comment by simi-dev** [comment]
Indeed i want to make zero-fees transaction so i've skipped --fees flag and in json amount of uatom is null ... i must change something in gaia cmd's ? 

thanks

**Comment by simi-dev** [comment]
@cwgoes thanks for your help this is one of the tx that we spoke about :
  TxHash: D90D08F237B92EF17EAFBECE579802B4F5513ACD372074454AD5C71D6253EFD1

**Comment by cwgoes** [comment]
I expect this is no longer relevant. If you have further troubles ask in the Gaia chat.
