### ISSUE TITLE
How to edit validator details without fees

### ISSUE THREAD

**Issue by simi-dev** [cosmos/launch#123]
Steps for OFFLINE method:
*if your validator address is on a ledger device on step 3 add --ledger flag in order to sign the transaction from it

1. run a full node with minimum-gas-prices = ""

2. `gaiacli tx staking edit-validator --moniker="<moniker_name>" --website="<website>" --identity="<identity_generated_on_www.keybase.io>" --details="<validator_description> --chain-id=cosmoshub-1 --from=<key_alias> --commission-rate="<new_commision_value>" --node="<ip_of_the_node_from_step_1>:26657" --generate-only > editValidatorUnsignedTx.json`

3. `gaiacli tx sign editValidatorUnsignedTx.json --offline --chain-id="cosmoshub-1" --indent --from=<key_alias> > editValidatorSignedTx.json`

4. `gaiacli tx broadcast editValidatorSignedTx.json --from=<key_alias> --chain-id="cosmoshub-1" --node="<ip_of_the_node_from_step_1>:26657"`

*if you need more details you can contact me at riot : @goldel:matrix.org

**Comment by jackzampolin** [comment]
@simi-dev thank you for the instructions! I think the forum (https://forum.cosmos.network) might be the best place for this!
