### ISSUE TITLE
Error with 'gaiad start'

### ISSUE THREAD

**Issue by juqiangl** [cosmos/launch#131]
Hi, 
I am using gaiad version 0.34, and genesis.JSON for cosmoshub-2.  When doing "gaiad start", saw  the following error. Any help is appreciated.

 gaiad start
I[2019-04-26|19:03:48.415] Starting ABCI with Tendermint                module=main 
ERROR: Error during handshake: Error on replay: Validator set is nil in genesis and still empty after InitChain

**Comment by alexanderbez** [comment]
Thanks for opening an issue @juqiangl, but this is not he repo for this. I noticed an SDK issue was opened. We can help you there.
