### ISSUE TITLE
Testnet or mainnet

### ISSUE THREAD

**Issue by ksemaev** [cosmos/launch#134]
Guys, I've read the docs and articles several times, and the link https://cosmos.network/docs/gaia/join-mainnet.html returnes 404.

I can't understand - where is that difference in files, configs, options etc when I want to start testnet instead of mainnet (or other way round)?

Please advice

**Comment by gamarin2** [comment]
The docs for testnet have moved: 

https://hub.cosmos.network/docs/join-testnet.html
https://hub.cosmos.network/docs/deploy-testnet.html

Currently, the docs for mainnet are still on the SDK repo (until `v0.36` is released):

https://cosmos.network/docs/cosmos-hub/join-mainnet.html#setting-up-a-new-node

When the Hub upgrades to SDK `v0.36` <> gaia `v1.0`, the mainnet docs will be here: 

https://cosmos.network/docs/cosmos-hub/join-mainnet.html

**Comment by ksemaev** [comment]
@gamarin2 TY, I saw the instruction and the part that confused me is that it says "Fetch the **testnet's** genesis.json" here: https://cosmos.network/docs/cosmos-hub/join-mainnet.html#genesis-seeds

So if https://github.com/cosmos/launch/blob/master/genesis.json is really for mainnet, than I'm fine - TY
