### ISSUE TITLE
dialing peers failed

### ISSUE THREAD

**Issue by KimuraYu45z** [cosmos/launch#141]
https://github.com/cosmos/gaia/issues/304

This issue haven't solved yet...
Please help me...

I do only these process

```
git clone
git checkout ...
make install
gaiad init hoge --chain-id cosmoshub-3
wget .../genesis.json
cp genesis.json ~/.gaiad/config.json
vi ~/.gaiad/config/config.toml # writing seeds
gaiad start
```

**Comment by alexanderbez** [comment]
Hey @KimuraYu45z, no need to create another issue. I'll comment on the original
