### ISSUE TITLE
Implementation of 5% Slashing

### ISSUE THREAD

**Issue by crainbf** [cosmos/launch#4]
In the launch document it mentions this:

> ATOMs staked during genesis will be at risk of 5% slashing if your validator double signs.

Previously, my understanding was that the slashing penalty would be 20%. Does this mean this parameter has been changed to 5% in general? i.e. both validators' own ATOMs and delegations would be slashed by that amount? And atoms staked after genesis would also be subject to this potential penalty? (It would seem strange to me if atoms staked after genesis or delegated would be subject to different slashing penalties.)

For what it's worth, I think 5% is a very reasonable starting value and having governance adjust that later if needed is the right way to go.

**Comment by zmanian** [comment]
Yeah It will be 0.05% until governance decides to change it.

20% is too much security for this stage of the network.
