### ISSUE TITLE
More customizable gentx.json creation

### ISSUE THREAD

**Issue by nylira** [cosmos/launch#48]
There have been lots of questions about how to add **identity**, **website**, and **details** to one's own validator genTx pull request. Through trial and error I've come up with the following, which passes Certus One's validation bot. I propose adding this to the readme to assist validators for the next 21 hours and 20 minutes.

## `genTx` Process

Create unsignedTx.json:

```
gaiacli tx staking create-validator \
  --amount=20000000000uatom \
  --pubkey=$(gaiad tendermint show-validator) \
  --moniker="nylira" \
  --identity="6A0D65E29A4CBC8E" \
  --website="nylira.net" \
  --details="Nylira is a Cosmos validator service run by Peng Zhong @zcpeng" \
  --from=$ACCOUNT \
  --commission-rate="0.1" \
  --commission-max-rate="1.0" \
  --commission-max-change-rate="0.01" \
  --min-self-delegation 1000000 \
  --generate-only > unsignedTx.json
```

Create signedTx.json:

```
gaiacli tx sign unsignedTx.json --offline --ledger --chain-id="cosmoshub-1" --indent > signedTx.json
```

Then with the `signedTx.json` in hand, fork this repository and place it in `./launch/gentx/`, and rename it to be the same as your moniker.

## What is a `uatom`?

Note: `1uatom` is equal to 1/1,000,000th of an atom. So however many atoms you wish to delegate to your validator, multiple by one million for the `uatom` value.

## Where can I get an `identity` value?

The `identity` is a 16 character long hexadecimal value that you can generate with Keybase. It's a PGP public key. [Here's mine for example.](https://keybase.io/peng)

**Comment by cwgoes** [comment]
Closing as the genesis ceremony has finished. Thanks @nylira!
